#!/bin/bash

# iconcache -- Revision: 111r1 -- by eznix (https://sourceforge.net/projects/eznixos/)
# (GNU/General Public License version 3.0)

iconcacher () {
  gtk-update-icon-cache -f /usr/share/icons/breeze/
  gtk-update-icon-cache -f /usr/share/icons/breeze-dark/
  gtk-update-icon-cache -f /usr/share/icons/ePapirus/
  gtk-update-icon-cache -f /usr/share/icons/gnome/
  gtk-update-icon-cache -f /usr/share/icons/Papirus/
  gtk-update-icon-cache -f /usr/share/icons/Papirus-Dark/
  gtk-update-icon-cache -f /usr/share/icons/Papirus-Light/
  gtk-update-icon-cache -f /usr/share/icons/Tango/
}

iconcacher

done

# Disclaimer:

# THIS SOFTWARE IS PROVIDED BY EZNIX “AS IS” AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO
# EVENT SHALL EZNIX BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
# BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER
# IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
